### ISSUE TITLE
Using Sold Out Badges Within Divi

### ISSUE THREAD

**Issue by GraphicBird-Designs** [CharlieEtienne/sold-out-badge-for-woocommerce#1]
Hello!

Really great idea for a plugin :) I'm just struggling to make it work with my Divi Theme. I've used the Divi Theme Builder to create my product pages and the Sold Out badge doesn't show on any of the items. Do you have any suggestions?

Thanks :)

**Comment by chucknology667** [comment]
Same here.

**Comment by CharlieEtienne** [comment]
Hi @GraphicBird-Designs and @chucknology667 

I'll publish an update with this fix tonight, but if you don't want to wait, you can try to add this CSS code:

```css
.wcsob_soldout {
    z-index:9;
}
```

**Comment by CharlieEtienne** [comment]
You shoud be able to update. 

Cheers,

Charlie
