### ISSUE TITLE
Badge Showing Even if Variation is In Stock

### ISSUE THREAD

**Issue by katvondiesel** [CharlieEtienne/sold-out-badge-for-woocommerce#11]
Hey Charlie, 

We have a few items that are variations and the out of stock badge shows on them even if one of the variations is in stock. Is there a way for it not to show if a variation of the specific product is in stock? 

Example - 434
434-1 (OOS)
434-2 (OOS)
434-3 In stock but badge still shows 

![Screenshot 2021-08-17 111322](https://user-images.githubusercontent.com/87150086/129752694-25f2a344-2a74-4581-b1cc-72845ab8c420.png)

**Comment by ChaotiX66** [comment]
Hi there!

We also have this problem, but for our site which is in English and Japanese, it is only on some random product variations on the Japanese translations where the badge is shown, even though the product is in stock.

**Comment by CharlieEtienne** [comment]
Hi @katvondiesel and @ChaotiX66,

I'm starting digging into this issue and I don't manage to reproduce it unless I check _Enable stock management at product level_ checkbox... Make sure you didn't check this option in Product data > Inventory

Keep me informed

Charlie
