### ISSUE TITLE
position of sold out badge

### ISSUE THREAD

**Issue by samborst** [CharlieEtienne/sold-out-badge-for-woocommerce#12]
![Schermafbeelding 2021-11-22 om 17 03 00](https://user-images.githubusercontent.com/94855717/142894677-2f477754-cf03-4e4d-9d15-fe698ed8ab14.png)
How can I change the position of the sold out badge? As you can see in the attached screenshot the position now is somewhat strange. I would like it to be on the image.

**Comment by CharlieEtienne** [comment]
Hi,

Indeed, it shouldn't be there. However the badge has a necessary absolute position so it can vary depending of the theme you're using. You could try with a bit of CSS to adjust its position. Please provide a link if you want some help with CSS
