### ISSUE TITLE
Latest update (ver 3.0.0) breaks plugin

### ISSUE THREAD

**Issue by 777Nova777** [CharlieEtienne/sold-out-badge-for-woocommerce#14]
The latest update breaks the plugin. After rolling back to previous version (2.2.0) it works again.

**Comment by CharlieEtienne** [comment]
Hi,

Sorry to hear that and thanks for alerting me. Could you be more precise? Did you get some error message, or just positionning issues?

**Comment by CharlieEtienne** [comment]
For some reason, "position: absolute" CSS rule was missing. This is fixed in 3.0.1 and you should be able to update.

Thanks,

Charlie

**Comment by 777Nova777** [comment]
Thank you very much!Sent from my Galaxy
-------- Original message --------From: Charlie Etienne ***@***.***> Date: 27/02/2022  14:16  (GMT+02:00) To: CharlieEtienne/sold-out-badge-for-woocommerce ***@***.***> Cc: 777Nova777 ***@***.***>, Author ***@***.***> Subject: Re: [CharlieEtienne/sold-out-badge-for-woocommerce] Latest update
  (ver 3.0.0) breaks plugin (Issue #14) 
For some reason, "position: absolute" CSS rule was missing. This is fixed in 3.0.1 and you should be able to update.
Thanks,
Charlie
