### ISSUE TITLE
does this plugin work with WooCommerce Version 6.3.1?

### ISSUE THREAD

**Issue by kitka** [CharlieEtienne/sold-out-badge-for-woocommerce#15]
I have just updated and my Sold badges seem to have disappeared. Is it still working?

**Comment by CharlieEtienne** [comment]
Hi @kitka, could you give me a link to your site ?

Thanks,

Charlie

**Comment by kitka** [comment]
Hi Charlie,

It is a test site. I can give you a login: 

https://kitka.net.au/artitja/wp-admin/ <https://kitka.net.au/artitja/wp-admin/>

User charlie
Password  nXhbK%XfRoQCMr

You will find a product that is sold but the sold label only shows when viewing the individual product. It used to work on the product archive page but now doesn’t.

https://kitka.net.au/artitja/product/bush-yam/ <https://kitka.net.au/artitja/product/bush-yam/>
https://kitka.net.au/artitja/product-category/paintings/ <https://kitka.net.au/artitja/product-category/paintings/> 

Thanks for your help!



Kitka Hiltula
***@***.***

**Comment by CharlieEtienne** [comment]
It seems you're using Archive posts instead of Archive products in Elementor theme builder. That's why it doesn't display the badge. I just published a new version (4.3.1) and updated it on your site. It seems to work fine now.

Cheers,

Charlie

**Comment by kitka** [comment]
THANK YOU! 



Kitka Hiltula
***@***.***
