### ISSUE TITLE
Badge not displaying

### ISSUE THREAD

**Issue by ShapeshiftingEli** [CharlieEtienne/sold-out-badge-for-woocommerce#4]
Pretty much everything is sold out here: https://shapeshifters.co/product-category/garments/binders/

Is it the theme? Too many variations? I'm mystified.

**Comment by CharlieEtienne** [comment]
Hi @ShapeshiftingEli 

I can see you managed to do it in pure css, which is even better than a plugin. Good for you! And sorry for the delay

Charlie
