### ISSUE TITLE
Toggle on/off for a specific product

### ISSUE THREAD

**Issue by smellcoffee** [CharlieEtienne/sold-out-badge-for-woocommerce#9]
Hi,
Thanks for bringing this plugin to life.

Is there a way to turn off the "Sold Out" on a per-product basis? 

I have something that will soon be available for the first time and I'd like to have the page live. 
The product has no stock since it isn't launched yet but shows "Sold Out" since the stock is set to 0. It's a little confusing since its' never been sold and I use "Sold Out" for everything that is "Sold Out";-)

Can I turn this off somehow for this page?

A toggle on the stock General Tab in Woocommerce's Product data section for the page would work great.

![Sold-Out-Badge-for-Woocommerce](https://user-images.githubusercontent.com/22917199/125678757-e0ebcad0-d686-48c0-9f31-43e6c018a03b.jpg)

**Comment by CharlieEtienne** [comment]
Added in [3.1](https://github.com/CharlieEtienne/sold-out-badge-for-woocommerce/releases/tag/3.1.0) 🎉
